"""empty message

Revision ID: 24f7265942c1
Revises: 
Create Date: 2024-06-09 18:20:30.335771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f7265942c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('continent', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('mannerism', sa.String(), nullable=True),
    sa.Column('visa', sa.String(), nullable=True),
    sa.Column('tipping', sa.String(), nullable=True),
    sa.Column('when', sa.String(), nullable=True),
    sa.Column('links', sa.String(), nullable=True),
    sa.Column('phrases', sa.String(), nullable=True),
    sa.Column('foods', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favorites_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries_table.id'], name=op.f('fk_favorites_table_country_id_countries_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_favorites_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_table')
    op.drop_table('users_table')
    op.drop_table('countries_table')
    # ### end Alembic commands ###
